version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    container_name: db_account_api
    env_file:
      - '.env'
    ports:
      - 5433:5432
    volumes:
      - pgdata13:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - '.env'
    depends_on:
      - postgres
    container_name: account_api
    volumes:
      - '~/.bash_history:/.bash_history'
    ports:
      - 3042:3042

volumes:
  pgdata13:
